<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
### Hidden Layer:
### Output Layer:
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
import numpy as np
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

correct_outputs = [[1], [1], [1], [0]]
# inputs = np.array([
#     [0,0,1],
#     [1,0,1],
#     [0,1,1],
#     [1,1,0]
# ])

# INPUTTING LAST COLUMN AS 1, 1, 1, 1, BECAUSE IT IS CONSIDERED A
#  'STANDARD BIAS TERM' (PARAPHRASED FROM CRAWFORD COLLINS)
#  WHICH NEEDS TO BE INCLUDED(?) TO HELP CALCULATE THE WEIGHTS 
#  PROPERLY (?)

inputs = np.array([
    [0,0,1],
    [1,0,1],
    [0,1,1],
    [1,1,1]
])

In [2]:
# inputs = np.array([
#     [0,1,0,1],
#     [0,0,1,1],
#     [1,1,1,0]
# ])

#### Step activation function

In [3]:
# ##### Your Code Here #####

# # STEP FUNCTION
# # def step_function(x):
# #     if 1 >= x >=.5:
# #         return True
# #     if 0 <= x <.5:
# #         return 0

# def step_function(x):
#     a = np.piecewise(x, [x < .5, x >= .5], [0, 1])
#     return a

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

#### Step activation function derivative

In [4]:
# def step_function_derivative(x):
#     sx = step_function(x)
#     return sx *(1-sx)

### Initialize random weights for our four inputs

In [5]:
np.random.seed(812)
weights = np.random.random((3,1))
weights

array([[0.5049808 ],
       [0.60592761],
       [0.45748719]])

### Calculate weighted sum of inputs and weights

In [6]:
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[0.45748719],
       [0.96246799],
       [1.06341479],
       [1.5683956 ]])

### Output the activated value for the end of 1 training epoch

In [7]:
activated_outputs = sigmoid(weighted_sum)
activated_outputs

array([[0.6124179 ],
       [0.72361567],
       [0.74334258],
       [0.82755477]])

### Output the activated value for the end of 1 training epoch


In [8]:
error = correct_outputs - activated_outputs
error

array([[ 0.3875821 ],
       [ 0.27638433],
       [ 0.25665742],
       [-0.82755477]])

### take difference of output and true values to calculate error


In [9]:
adjustments = error * sigmoid_derivative(activated_outputs)
adjustments

array([[ 0.08834937],
       [ 0.06078562],
       [ 0.05605741],
       [-0.17514999]])

#### WEIGHT CORRELATED WITH CLOSENESS OF THE ORIGINAL INPUTS AND THE *CORRECT_OUTPUTS*

In [10]:
weights += np.dot(inputs.T, adjustments)
weights

array([[0.39061643],
       [0.48683502],
       [0.48752959]])

#### Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate.

In [11]:
# Steps we've already done: 
# 1. Randomly Initialized Weights already. Those are in memory as `weights`
# 2. We've already got input data & correct_outputs


# Update our weights 10,000 times - (fingers crossed that this process reduces error)
for iteration in range(100000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # CaLculation error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(activated_output)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-16.45547116]
 [-16.45547116]
 [ 24.73140216]]
Output after training
[[1.00000000e+00]
 [9.99745491e-01]
 [9.99745491e-01]
 [2.80255057e-04]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [12]:
db = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
db.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [13]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(db)[:-1]
feats

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']

In [14]:
X = db.drop(columns='Outcome')
y = db.drop(columns=feats)

#### SCALING THE X DATA FOR FASTER TRAINING

In [15]:
scaler = MinMaxScaler()

In [16]:
X_scaled = scaler.fit_transform(X)

In [17]:
X_scaled

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [18]:
# ##### Update this Class #####

# class Perceptron(object):
    
#     def __init__(self, niter = 10):
#     self.niter = niter
    
#     def __sigmoid(self, x):
#         return None
    
#     def __sigmoid_derivative(self, x):
#         return None

#     def fit(self, X, y):
#     """Fit training data
#     X : Training vectors, X.shape : [#samples, #features]
#     y : Target values, y.shape : [#samples]
#     """

#     # Randomly Initialize Weights
#     weights = ...

#     for i in range(self.niter):
#         # Weighted sum of inputs / weights

#         # Activate!

#         # Cac error

#         # Update the Weights


#     def predict(self, X):
#     """Return class label after unit step"""
#         return None

In [19]:
# ##### Update this Class #####

# class Perceptron(object):
    
#     def __init__(self, niter = 10):
#         self.niter = niter
    
#     def __sigmoid(self, x):
#         return 1 / (1 + np.exp(-x))
    
#     def __sigmoid_derivative(self, x):
#         sx = sigmoid(x)
#         return sx * (1-sx)

#     def fit(self, X, y):
#         """Fit training data
#         X : Training vectors, X.shape : [#samples, #features]
#         y : Target values, y.shape : [#samples]
#         """

#     # Randomly Initialize Weights
#     weights = ...

#     for i in range(self.niter):
#         # Weighted sum of inputs / weights
#         weighted_sum = np.dot(inputs, weights)
#         # Activate!
#         activated_outputs = sigmoid(weighted_sum)
#         # Cac error
#         error = correct_outputs - activated_outputs
#         # Update the Weights
#             weights += np.dot(inputs.T, adjustments)

#     def predict(self, X):
#         """Return class label after unit step"""
#         return None

In [20]:
# ##### Update this Class #####

# class Perceptron(object):
    
#     def __init__(self,rate=10, niter = 10):
#         self.rate = rate
#         self.niter = niter
    
#     def __sigmoid(self, x):
#         return 1 / (1 + np.exp(-x))
    
#     def __sigmoid_derivative(self, x):
#         sx = sigmoid(x)
#         return sx * (1-sx)

#     def fit(self, X, y):
#         """Fit training data
#         X : Training vectors, X.shape : [#samples, #features]
#         y : Target values, y.shape : [#samples]
#         """

#         # Randomly Initialize Weights
#         np.random.seed(812)
#         weights = np.random.random((3,1))

#         for i in range(self.niter):
#             # Weighted sum of inputs / weights
#             weighted_sum = np.dot(inputs, weights)
#             # Activate!
#             activated_outputs = sigmoid(weighted_sum)
#             # Cac error
#             error = correct_outputs - activated_outputs
#             # Update the Weights
#             weights += np.dot(inputs.T, adjustments)

#     def net_input(self, X):
#         """Calculate net input"""
#         return np.dot(X, self.weight[1:]) + self.weight[0]

#     def predict(self, X):
#         """Return class label after unit step"""
#         return np.where(self.net_input(X) >= 0.0, 1, -1)


In [21]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self,rate=10, niter = 10):
        self.rate = rate
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        np.random.seed(812)
        weights = np.random.random((3,1))

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(inputs, weights)
            # Activate!
            activated_outputs = sigmoid(weighted_sum)
            # Cac error
            error = correct_outputs - activated_outputs
            # Update the Weights
            weights += np.dot(inputs.T, adjustments)

    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.weight[1:]) + self.weight[0]

    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, -1)


In [22]:
pn = Perceptron(10)

In [23]:
pn.fit(X,y)

## DID NOT GET PREDICT FUNCTION WORKING: PLEASE ASSIST

In [24]:
pn.predict(X)

AttributeError: 'Perceptron' object has no attribute 'weight'

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?