<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:** = A neuron computes the weighted average of its inputs then passes the sum to an activation functino which determines how much of the signal is then passed on to the next neuron/layer.
- **Input Layer:** = The provider of initial, unprocessed information to the neaural network/hidden layers.
- **Hidden Layer:** = Isolated within the network with no contact to outside world, the bulk of the processing of data is usually done within the hidden layer. This layer eventually then transmits the results to the output layer.
- **Output Layer:** = Responsible for computation and eventual transmission/transferrance to the outside world.
- **Activation:** = (Function?) The function which takes in the weighted sums of inputs plus some bias term from the previous layer and outputs an activation value.
- **Backpropagation:** = A recursive process during model training which starts with randomly assigned weights for inputs/wires-between-layers and, through a repeating process of observing the output of the weights/neurons and comparing to known values, updates the weights of the previous layers to bring the predictions/observations closer to the known values.


## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [1]:
import pandas as pd
import numpy as np
candy = pd.read_csv('chocolate_gummy_bears.csv')
# candy_np = pd.read_csv('chocolate_gummy_bears.csv', header=None, skiprows=1)

In [2]:
candy.head()

chocolate  gummy  ate
0          0      1    1
1          1      0    1
2          0      1    1
3          0      0    0
4          1      1    0

In [3]:
candy['bias'] = 1

### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. Explain why you could not achieve a higher accuracy with a *simple perceptron*. It's possible to achieve ~95% accuracy on this dataset.

In [4]:
np.random.seed(812)

In [5]:
# Start your candy perceptron here

X = candy[['chocolate', 'gummy','bias']].values
y = candy['ate'].values
correct_outputs = y.tolist()
correct_outputs_np = np.asarray(correct_outputs)

In [6]:
# inputs = candy.values
# inputs


In [7]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

np.random.seed(812)
weights = np.random.random((3,1))
weights

array([[0.5049808 ],
       [0.60592761],
       [0.45748719]])

In [8]:
weighted_sum = np.dot(X, weights)
weighted_sum

array([[1.06341479],
       [0.96246799],
       [1.06341479],
       ...,
       [1.06341479],
       [1.06341479],
       [0.96246799]])

In [9]:
activated_outputs = sigmoid(weighted_sum)
activated_outputs

array([[0.74334258],
       [0.72361567],
       [0.74334258],
       ...,
       [0.74334258],
       [0.74334258],
       [0.72361567]])

In [10]:
1/(1+np.exp(-1*weighted_sum))

array([[0.74334258],
       [0.72361567],
       [0.74334258],
       ...,
       [0.74334258],
       [0.74334258],
       [0.72361567]])

In [11]:
activated_outputs.shape

(10000, 1)

In [12]:
len(correct_outputs)

10000

In [13]:
y_shaped = np.reshape(y, (10000,1))
y_shaped.shape

(10000, 1)

In [14]:
y_shaped[0:10]

array([[1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

In [15]:
# adjustments[0:50]

In [16]:
activated_outputs[0:10]

array([[0.74334258],
       [0.72361567],
       [0.74334258],
       [0.6124179 ],
       [0.82755477],
       [0.74334258],
       [0.6124179 ],
       [0.82755477],
       [0.6124179 ],
       [0.6124179 ]])

In [17]:
y_shaped[0:10]

array([[1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

In [18]:
error = y_shaped - activated_outputs
error[0:10]

array([[ 0.25665742],
       [ 0.27638433],
       [ 0.25665742],
       [-0.6124179 ],
       [-0.82755477],
       [ 0.25665742],
       [-0.6124179 ],
       [-0.82755477],
       [-0.6124179 ],
       [-0.6124179 ]])

In [19]:
# error_df = pd.DataFrame(data=error)
# error_df

In [20]:
 error.shape

(10000, 1)

In [21]:
adjustments = error * sigmoid_derivative(activated_outputs)
adjustments[0:10]

array([[ 0.05605741],
       [ 0.06078562],
       [ 0.05605741],
       [-0.13960071],
       [-0.17514999],
       [ 0.05605741],
       [-0.13960071],
       [-0.17514999],
       [-0.13960071],
       [-0.13960071]])

In [22]:
adjustments.shape

(10000, 1)

In [23]:
X.T.shape

(3, 10000)

In [24]:
weights += np.dot(X.T, adjustments)
weights

array([[-285.38531925],
       [-296.96183722],
       [-493.77958388]])

In [25]:
for iteration in range(1000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(X, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # CaLculation error
    error = y_shaped - activated_output
    
    adjustments = error * sigmoid_derivative(activated_output)*.01
    
    # Update the Weights
    weights += np.dot(X.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[4.78190965]
 [4.78380389]
 [8.60172108]]
Output after training
[[0.00624753]
 [0.00625124]
 [0.00624753]
 ...
 [0.00624753]
 [0.00624753]
 [0.00625124]]


#### NOT SURE WHY WEIGHTS ARE TRAINING TO THE SAME POLARITY (+/-)
####  2 OF THE 3 SHOULD HAVE OPPOSITE POLARITY (+/-) OF THE 3RD WEIGHT
####  IN ORDER TO PROPERLY PREDICT THE CHOCOLATE-GUMMY/NAND-GATE PROBLEM

In [26]:
error[0:20]

array([[ 0.99375247],
       [ 0.99374876],
       [ 0.99375247],
       [-0.02529353],
       [-0.00152168],
       [ 0.99375247],
       [-0.02529353],
       [-0.00152168],
       [-0.02529353],
       [-0.02529353],
       [ 0.99375247],
       [-0.00152168],
       [-0.02529353],
       [ 0.99375247],
       [ 0.99375247],
       [-0.00625124],
       [ 0.99374876],
       [ 0.99375247],
       [-0.00152168],
       [ 0.99375247]])

In [27]:
activated_output[0:50]

array([[0.00624753],
       [0.00625124],
       [0.00624753],
       [0.02529353],
       [0.00152168],
       [0.00624753],
       [0.02529353],
       [0.00152168],
       [0.02529353],
       [0.02529353],
       [0.00624753],
       [0.00152168],
       [0.02529353],
       [0.00624753],
       [0.00624753],
       [0.00625124],
       [0.00625124],
       [0.00624753],
       [0.00152168],
       [0.00624753],
       [0.00624753],
       [0.00624753],
       [0.00152168],
       [0.00152168],
       [0.00625124],
       [0.00625124],
       [0.02529353],
       [0.02529353],
       [0.02529353],
       [0.02529353],
       [0.00625124],
       [0.00624753],
       [0.00152168],
       [0.00625124],
       [0.00625124],
       [0.00624753],
       [0.00624753],
       [0.00152168],
       [0.02529353],
       [0.00625124],
       [0.00625124],
       [0.02529353],
       [0.00152168],
       [0.00624753],
       [0.00625124],
       [0.00152168],
       [0.02529353],
       [0.006

In [28]:
adjustments[0:20]

array([[ 2.48435693e-03],
       [ 2.48434762e-03],
       [ 2.48435693e-03],
       [-6.32237187e-05],
       [-3.80419493e-06],
       [ 2.48435693e-03],
       [-6.32237187e-05],
       [-3.80419493e-06],
       [-6.32237187e-05],
       [-6.32237187e-05],
       [ 2.48435693e-03],
       [-3.80419493e-06],
       [-6.32237187e-05],
       [ 2.48435693e-03],
       [ 2.48435693e-03],
       [-1.56279548e-05],
       [ 2.48434762e-03],
       [ 2.48435693e-03],
       [-3.80419493e-06],
       [ 2.48435693e-03]])

In [29]:
activated_output

array([[0.00624753],
       [0.00625124],
       [0.00624753],
       ...,
       [0.00624753],
       [0.00624753],
       [0.00625124]])

In [30]:
rounded = np.around(activated_output)
rounded

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [31]:
from sklearn.metrics import accuracy_score
y_pred = rounded
y_true = y_shaped
accuracy_score(y_true, y_pred)

0.5

#### Needs more nodes? Not certain on why the score was so low with a simple perceptron

### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset. 

In [32]:
# I want activations that correspond to negative weights to be lower
# and activations that correspond to positive weights to be higher

class NeuralNetwork:
    def __init__(self):
        # Set up Architecture of Neural Network
        self.inputs = 3
        self.hiddenNodes = 1
        self.outputNodes = 1

        # Initial Weights
        # 3x1 Matrix Array for the First Layer
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
       
        # 1x1 Matrix Array for Hidden to Output
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        aka "predict"
        """
        
        # Weighted sum of inputs => hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final activation of output
        self.activated_output = self.sigmoid(self.output_sum) 
        
        return self.activated_output
        
    def backward(self, X,y_shaped,o):
        """
        Backward propagate through the network
        """
        
        # Error in Output
        self.o_error = y_shaped - o
        
        # Apply Derivative of Sigmoid to error
        # How far off are we in relation to the Sigmoid f(x) of the output
        # ^- aka hidden => output
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        # z2 error
        self.z2_error = self.o_delta.dot(self.weights2.T)
        # How much of that "far off" can explained by the input => hidden
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        # Adjustment to first set of weights (input => hidden)
        self.weights1 += X.T.dot(self.z2_delta)
        # Adjustment to second set of weights (hidden => output)
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        

    def train(self, X, y_shaped):
        o = self.feed_forward(X)
        self.backward(X,y_shaped,o)

In [33]:
nn = NeuralNetwork()

In [ ]:
for i in range(10000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y_shaped)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y_shaped - nn.feed_forward(X)))))
    nn.train(X,y_shaped)

+---------EPOCH 1---------+
Input: 
 [[0 1 1]
 [1 0 1]
 [0 1 1]
 ...
 [0 1 1]
 [0 1 1]
 [1 0 1]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.54170017]
 [0.53821391]
 [0.54170017]
 ...
 [0.54170017]
 [0.54170017]
 [0.53821391]]
Loss: 
 0.2513994616679112
+---------EPOCH 2---------+
Input: 
 [[0 1 1]
 [1 0 1]
 [0 1 1]
 ...
 [0 1 1]
 [0 1 1]
 [1 0 1]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.20514292]
 [0.02190297]
 [0.20514292]
 ...
 [0.20514292]
 [0.20514292]
 [0.02190297]]
Loss: 
 0.40957837555708776
+---------EPOCH 3---------+
Input: 
 [[0 1 1]
 [1 0 1]
 [0 1 1]
 ...
 [0 1 1]
 [0 1 1]
 [1 0 1]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.5]
 [0.5]
 [0.5]
 ...
 [0.5]
 [0.5]
 [0.5]]
Loss: 
 0.25
+---------EPOCH 4---------+
Input: 
 [[0 1 1]
 [1 0 1]
 [0 1 1]
 ...
 [0 1 1]
 [0 1 1]
 [1 0 1]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.5]
 [0.5]
 [0.5]
 ..

#### SAME ISSUE AS EARLIER; 
####  NOT SURE WHY WEIGHTS ARE TRAINING TO THE SAME POLARITY (+/-)
####  2 OF THE 3 SHOULD HAVE OPPOSITE POLARITY (+/-) OF THE 3RD WEIGHT
####  IN ORDER TO PROPERLY PREDICT THE CHOCOLATE-GUMMY/NAND-GATE PROBLEM

P.S. Don't try candy gummy bears. They're disgusting. 

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

In [ ]:
df['bias'] = 1

In [ ]:
df.columns

In [ ]:
X = df[['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal','bias']].values
y = df['target'].values

#### BELOW TUNING: NODES (14)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model1 = Sequential(name="1")

model1.add(Dense(14, input_dim=14, activation='relu', name="Dense1"))
model1.add(Dense(14, activation='relu'))
model1.add(Dense(14, activation='relu'))
model1.add(Dense(1, activation='sigmoid'))

model1.compile(loss='binary_crossentropy', optimizer='adam',
              metrics=['accuracy'])

# Let's inspect our new architecture
model1.summary()

In [ ]:
#VALIDATION SPLIT SAVES .N OF YOUR DATA (HERE=10%) FOR VALIDATION ACCURACY
model1.fit(X,y, epochs=250, validation_split=.10, verbose=False)

In [ ]:
scores = model1.evaluate(X,y, verbose=0)
print(f"{model1.metrics_names[1]}: {scores[1]*100}")

### ACCURACY OF 86.7986798286438 NODES (14)

#### BELOW TUNING: NODES = 28

In [ ]:
model2 = Sequential(name="2")

model2.add(Dense(28, input_dim=14, activation='relu', name="Dense1"))
model2.add(Dense(28, activation='relu'))
model2.add(Dense(28, activation='relu'))
model2.add(Dense(1, activation='sigmoid'))

model2.compile(loss='binary_crossentropy', optimizer='adam',
              metrics=['accuracy'])

# Let's inspect our new architecture
model2.summary()

In [ ]:
#VALIDATION SPLIT SAVES .N OF YOUR DATA (HERE=10%) FOR VALIDATION ACCURACY
model2.fit(X,y, epochs=250, validation_split=.10, verbose=False)

In [ ]:
scores = model2.evaluate(X,y, verbose=0)
print(f"{model2.metrics_names[1]}: {scores[1]*100}")

### ACCURACY OF 86.7986798286438 NODES (28)

In [ ]:
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
import numpy as np

In [ ]:
def create_model():
    # create model
    model3 = Sequential(name="3")
    model3.add(Dense(28, input_dim=14, activation='relu', name="Dense1"))
    model3.add(Dense(28, activation='relu'))
    model3.add(Dense(28, activation='relu'))
    model3.add(Dense(1, activation='sigmoid'))
    # Compile model
    model3.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model3

In [ ]:
np.random.seed(842)
model3 = KerasClassifier(build_fn=create_model, verbose=0)

In [ ]:
param_grid = {'batch_size': [10,15, 20,30, 40, 60, 80, 100],
              'epochs': [20,40,60]}

In [ ]:
grid = GridSearchCV(estimator=model3, param_grid=param_grid, n_jobs=-1)
grid_result = grid.fit(X, y)

In [ ]:
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

####  GRID SEARCH RESULTS
####  BEST BATCH SIZE = 15 (VIA GRID SEARCH)
####  BEST EPOCH SIZE = 60 (HIGHER = BETTER)(VIA GRID SEARCH)

In [ ]:
model4 = Sequential(name="4")

model4.add(Dense(28, input_dim=14, activation='relu', name="Dense1"))
model4.add(Dense(28, activation='relu'))
model4.add(Dense(28, activation='relu'))
model4.add(Dense(1, activation='sigmoid'))

model4.compile(loss='binary_crossentropy', optimizer='adam',
              metrics=['accuracy'])

# Let's inspect our new architecture
model4.summary()

In [ ]:
#VALIDATION SPLIT SAVES .N OF YOUR DATA (HERE=10%) FOR VALIDATION ACCURACY
model4.fit(X,y, batch_size=80, epochs=1500, validation_split=.10, verbose=False)

In [ ]:
scores = model4.evaluate(X,y, verbose=0)
print(f"{model4.metrics_names[1]}: {scores[1]*100}")

####  HYPERPARAMETERS TUNED: BATCH (80), EPOCH SIZE (1500), AND NODES (28)
####  BEST ACCURACY SCORE: GIVES ALTERNATING VALUES OF 45.54455578327179 OR 87.78877854347229....

In [ ]:
model5 = Sequential(name="5")

model5.add(Dense(14, input_dim=14, activation='relu', name="Dense1"))
model5.add(Dense(14, activation='relu'))
model5.add(Dense(14, activation='relu'))
model5.add(Dense(1, activation='sigmoid'))

model5.compile(loss='binary_crossentropy', optimizer='adam',
              metrics=['accuracy'])

# Let's inspect our new architecture
model5.summary()

In [ ]:
#VALIDATION SPLIT SAVES .N OF YOUR DATA (HERE=10%) FOR VALIDATION ACCURACY
model5.fit(X,y, batch_size=15, epochs=1500, validation_split=.10, verbose=False)

In [ ]:
scores = model5.evaluate(X,y, verbose=0)
print(f"{model5.metrics_names[1]}: {scores[1]*100}")

####  HYPERPARAMETERS TUNED: BATCH (15), EPOCH SIZE (1500) AND NODES (14)
####  BEST ACCURACY SCORE: 88.11880946159363

In [ ]:
model6 = Sequential(name="6")

model6.add(Dense(14, input_dim=14, activation='relu', name="Dense1"))
model6.add(Dense(14, activation='relu'))
model6.add(Dense(28, activation='relu'))
model6.add(Dense(1, activation='sigmoid'))

model6.compile(loss='binary_crossentropy', optimizer='adam',
              metrics=['accuracy'])

# Let's inspect our new architecture
model6.summary()

In [ ]:
#VALIDATION SPLIT SAVES .N OF YOUR DATA (HERE=10%) FOR VALIDATION ACCURACY
model7.fit(X,y, batch_size=15, epochs=1500, validation_split=.10, verbose=False)

In [ ]:
scores = model7.evaluate(X,y, verbose=0)
print(f"{model7.metrics_names[1]}: {scores[1]*100}")

# HYPERPARAMETERS TUNED: BATCH (15), EPOCH SIZE(1500), NODES(14/28)
# BEST ACCURACY SCORE: 99.01

In [ ]:
model7 = Sequential(name="7")

model7.add(Dense(14, input_dim=14, activation='relu', name="Dense1"))
model7.add(Dense(14, activation='relu'))
model7.add(Dense(28, activation='relu'))
model7.add(Dense(1, activation='sigmoid'))

model7.compile(loss='binary_crossentropy', optimizer='adam',
              metrics=['accuracy'])

# Let's inspect our new architecture
model7.summary()

In [ ]:
#VALIDATION SPLIT SAVES .N OF YOUR DATA (HERE=10%) FOR VALIDATION ACCURACY
model7.fit(X,y, batch_size=15, epochs=40, validation_split=.10, verbose=False)

In [ ]:
scores = model7.evaluate(X,y, verbose=0)
print(f"{model7.metrics_names[1]}: {scores[1]*100}")